from typing import List, Optional
from pydantic import BaseModel


# ---------------------------------------------------------------------------
# Layer 1: Inputs
# ---------------------------------------------------------------------------

class ProfileState(BaseModel):
    """Biological baseline. Set at onboarding, updated through hair evolution."""
    texture_type: str                        # 2A / 2B / 2C / 3A / 3B / 3C / 4A / 4B / 4C
    texture_label: str                       # e.g. "Dense Coils" — user-facing
    porosity: str                            # low / medium / high
    density: str                             # low / medium / high
    strand_thickness: Optional[str] = None  # fine / medium / coarse
    elasticity: Optional[str] = None        # low / normal / high
    scalp_state: Optional[str] = None       # dry / normal / oily / sensitive
    humidity_response: Optional[str] = None # high / moderate / low (sensitivity)
    hair_goals: Optional[List[str]] = None  # e.g. ["definition", "growth"]
    routine_flags: List[str] = []           # active flags from lookup tables
                                             # e.g. frizz_control, seal_moisture, strong_hold


class SessionSignal(BaseModel):
    """Current hair concern detected from conversation. Built by session_signal service."""
    absorption_blocked: bool = False
    hold_loss: bool = False
    breakage_active: bool = False
    buildup_present: bool = False
    coated_feel: bool = False
    confidence_score: float = 0.0
    evidence_quote: str = ""
    fallback_used: bool = False
    decision_state: Optional[str] = None    # repair_first / reset_first / None


class EnvironmentalContext(BaseModel):
    """External stressors from weather, water quality, etc. Built by environmental service."""
    humidity_level: Optional[str] = None    # low / medium / high
    heat_stress: Optional[str] = None       # low / high
    hard_water: Optional[bool] = None
    sweat_freq: Optional[str] = None        # low / high
    ac_exposure: Optional[str] = None       # low / high
    environmental_intent: Optional[str] = None  # reset_first / None


class SessionIntent(BaseModel):
    """
    How the user is engaging — tone, friction, journey position.
    Built by session_intent service (LLM-driven). Feeds the JTE.
    """
    journey_state: str                      # discovering / diagnosing / evaluating /
                                             # conversion_ready / reassurance /
                                             # post_purchase / troubleshooting
    intent_clarity: str                     # low / medium / high
    confidence_level: str                   # certain / unsure / overwhelmed
    friction_score: str                     # low / moderate / high
    emotional_state: str                    # frustrated / hopeful / neutral / fatigued


# ---------------------------------------------------------------------------
# Layer 2: Strategy Payload (Decision Engine output — always rules-based)
# ---------------------------------------------------------------------------

class RoutineConstraints(BaseModel):
    """
    Controls what the Adaptive Routine Builder produces.
    Generated by the Decision Engine from profile + signals.
    """
    step_count_target: int = 5
    mandatory_steps: List[str] = []         # e.g. ["clarify", "condition", "light_styler"]
    forbidden_steps: List[str] = []         # e.g. ["heavy_treatment", "protein_mask"]


class ProductFilters(BaseModel):
    """
    Controls which products the Recommendation Engine surfaces.
    Flags map directly to Pinecone metadata — used as hard filters, not semantic hints.
    """
    required_flags: List[str] = []          # e.g. ["chelating", "low_buildup_risk"]
    forbidden_flags: List[str] = []         # e.g. ["silicone", "heavy_butter"]
    ideal_hold_level: Optional[str] = None  # light / moderate / strong
    porosity_match: Optional[str] = None    # low / medium / high
    texture_match: Optional[str] = None     # e.g. "4B" — for texture-specific products


class JTEInput(BaseModel):
    """
    Structured context passed to the JTE.
    The JTE reads this and produces a delivery plan — it does not re-derive from raw conversation.
    """
    journey_state: str
    intent_clarity: str
    confidence_level: str
    friction_score: str
    emotional_state: str


class StrategyPayload(BaseModel):
    """
    The complete output of the Decision Engine.
    Consumed by: Adaptive Routine Builder, Product Recommendation Engine, JTE.
    """
    decision_state: Optional[str] = None    # repair_first / reset_first / hold_first /
                                             # balanced_routine_first / simplify_friction / None
    routine_constraints: RoutineConstraints = RoutineConstraints()
    product_filters: ProductFilters = ProductFilters()
    jte_input: JTEInput


# ---------------------------------------------------------------------------
# Layer 3: JTE Delivery Plan (JTE output — always rules-based)
# ---------------------------------------------------------------------------

class JTEDeliveryPlan(BaseModel):
    """
    How the response should be delivered.
    The Response Composer reads this alongside the Strategy Payload to compose the final reply.
    """
    response_mode: str                      # educate / reassure / compare / convert / troubleshoot
    response_depth: str                     # short / medium / long
    cta_pressure: str                       # none / soft / moderate / strong
    product_exposure: str                   # hidden / selective / routine_led / direct
    tone_profile: str                       # expert_calm / warm_reassuring /
                                             # direct_confident / simplified_supportive
    ask_strategy: str                       # no_question / one_clarifying_question /
                                             # proceed_with_best_guess
    readiness_band: str                     # low / medium / high
    readiness_score: int                    # raw score: (clarity + confidence + action_signals)
                                             #           - (friction + confusion + emotional_resistance)


# ---------------------------------------------------------------------------
# Layer 4: Response Composer Input (everything the composer needs)
# ---------------------------------------------------------------------------

class ResponseComposerInput(BaseModel):
    """
    Full context handed to the Response Composer (LLM call).
    Composer reads strategy + delivery plan and writes the actual response.
    """
    strategy_payload: StrategyPayload
    jte_delivery_plan: JTEDeliveryPlan
    profile_state: ProfileState
    env: Optional["EnvironmentalContext"] = None  # climate context for GCC-aware responses
    candidate_products: List[dict] = []          # filtered products from Pinecone
    recent_messages: List[dict] = []             # last N turns — composer must read user's actual words
    conversation_summary: Optional[str] = None   # from Librarian / memory layer


# ---------------------------------------------------------------------------
# Clarification layer (emitted when signal detection is inconclusive)
# ---------------------------------------------------------------------------

class ClarificationOption(BaseModel):
    label: str                          # plain-language option shown to the user
    signal_hint: Optional[str] = None  # which signal this answer implies, if any


class ClarificationRequest(BaseModel):
    question: str
    options: List[ClarificationOption]
