"""
Recommendation Agent: Generates adaptive routine recommendations based on signals, vitals, and alerts.
"""

import json
from typing import List, Dict, Optional, Any
from app.agents.llm_call.llm_call import run_llm_agent


async def generate_recommendations(
    user_id: str,
    user_metadata: Dict[str, Any],
    routine: Dict[str, Any],
    alerts: List[Dict],
    vitals: Dict[str, Any]
) -> List[Dict[str, str]]:
    """
    Generate 2-3 adaptive recommendations for a user based on their current state.

    Args:
        user_id: User identifier
        user_metadata: User's profile (first_name, location, hair_goals, etc.)
        routine: Current routine (5 steps with products)
        alerts: Last 3 unread alerts from alert_log
        vitals: Vitals summary (latest, average, history per category)

    Returns:
        List of recommendation dicts: {title, message, reasoning, routine_step_ref, recommendation_type}
    """

    # Build context for the LLM
    user_name = user_metadata.get("first_name", "User")
    location = user_metadata.get("location", "Unknown")
    hair_goals = user_metadata.get("primary_goal", "")

    # Summarize routine
    routine_summary = ""
    if isinstance(routine, dict) and "routine" in routine:
        steps = routine.get("routine", [])
        routine_summary = " → ".join([s.get("step", "") for s in steps[:5]]) if steps else "No routine"

    # Summarize recent alerts
    alert_summary = ""
    if alerts:
        alert_summary = " | ".join([a.get("prompt", "") for a in alerts[:3]])

    # Summarize vitals trends
    vitals_summary = ""
    if vitals:
        # Format: "Moisture: 6.5 (avg), Definition: 7 (avg), Scalp: 5 (avg)"
        parts = []
        for vital, data in vitals.items():
            if isinstance(data, dict):
                avg = data.get("average")
                if avg:
                    parts.append(f"{vital.capitalize()}: {avg:.1f}")
        vitals_summary = ", ".join(parts) if parts else "No vitals recorded yet"

    # Build the prompt
    prompt = f"""You are a luxury hair care concierge generating adaptive daily routine recommendations.

User: {user_name} in {location}, seeking: {hair_goals}
Current routine: {routine_summary}
Recent alerts: {alert_summary or "None"}
Vitals trend: {vitals_summary}

Generate 2-3 specific, actionable recommendations to help {user_name} optimize their routine TODAY.

For each recommendation, provide:
1. A short title (e.g. "Boost moisture with a hydrating mask")
2. A personalized message explaining why (reference their specific vitals/alerts if relevant)
3. Which routine step it affects (optional, e.g. "Condition")
4. The type: environmental | signal | habit

Output as JSON array only, no other text:
[
  {{
    "title": "...",
    "message": "...",
    "reasoning": "...",
    "routine_step_ref": "Cleanse" | "Condition" | "Treat" | "Moisturize" | "Style" | null,
    "recommendation_type": "environmental" | "signal" | "habit"
  }}
]

Return ONLY valid JSON, no markdown or extra text."""

    try:
        # Call LLM
        response = await run_llm_agent(prompt, model="gemini-2.5-flash-lite")

        # Parse JSON from response
        # The response might have "type": "content" format from streaming
        raw_text = response if isinstance(response, str) else str(response)

        # Extract JSON from the response
        json_start = raw_text.find("[")
        json_end = raw_text.rfind("]") + 1
        if json_start >= 0 and json_end > json_start:
            json_str = raw_text[json_start:json_end]
            recommendations = json.loads(json_str)
        else:
            print(f"[RECOMMENDATION AGENT] No JSON found in response: {raw_text[:200]}")
            return []

        # Validate and return
        if not isinstance(recommendations, list):
            recommendations = [recommendations]

        # Add metadata
        from datetime import datetime, timezone
        for rec in recommendations:
            rec["id"] = None  # Will be generated by DB
            rec["created_at"] = datetime.now(timezone.utc).isoformat()

        print(f"[RECOMMENDATION AGENT] Generated {len(recommendations)} recommendations for {user_id}")
        return recommendations[:3]  # Cap at 3

    except json.JSONDecodeError as e:
        print(f"[RECOMMENDATION AGENT] JSON parse error: {str(e)}")
        return []
    except Exception as e:
        print(f"[RECOMMENDATION AGENT] Error generating recommendations: {str(e)}")
        return []
